### ISSUE TITLE
MT bench tw is not working

### ISSUE THREAD

**Issue by adamlin120** [mtkresearch/TCEval#4]
https://github.com/mtkresearch/TCEval/blob/ad77e61f76b9d1f64aca923a0d293875ea18acf3/mt_bench_tw/readme.md?plain=1#L48

This raised an error about missing reference answer. Do we need that?

**Comment by ZoneTwelve** [comment]
+1

**Comment by ftmtk** [comment]
Uploaded please try again

**Comment by adamlin120** [comment]
Thanks @ftmtk !
Though I did [fork](https://github.com/adamlin120/TCEval) one and use the reference in the [huggingface dataset](https://huggingface.co/datasets/MediaTek-Research/TCEval-v2) as suggested by @GitYCC per offline discussion.
